class Assets:
    class Pictures:
        RED_BRIGHTNESS = 'https://planet-story.s3.amazonaws.com/red_star.png'
        BLUE_BRIGHTNESS = 'https://planet-story.s3.amazonaws.com/blue_star.png'
        YELLOW_BRIGHTNESS = 'https://planet-story.s3.amazonaws.com/yellow_star.png'
        BLUE_DWARF = 'https://planet-story.s3.amazonaws.com/blue_dwarf.png'
        BLUE_GIANT = 'https://planet-story.s3.amazonaws.com/blue_giant.png'
        BLUE_SUPER_GIANT = 'https://planet-story.s3.amazonaws.com/blue_super_giant.png'
        
        BLUE_YOUNG_DWARF = 'https://planet-story.s3.amazonaws.com/Stars/Blue/Young/blue-young-dwarf.png'
        BLUE_YOUNG_DWARF = 'https://planet-story.s3.amazonaws.com/Stars/Blue/Young/blue-young-giant.png'
        BLUE_YOUNG_SUPER = 'https://planet-story.s3.amazonaws.com/Stars/Blue/Young/blue-young-super.png'
        BLUE_MIDDLE_DWARF = 'https://planet-story.s3.amazonaws.com/Stars/Blue/Middle/blue-middle-dwarf.png'
        BLUE_MIDDLE_GIANT = 'https://planet-story.s3.amazonaws.com/Stars/Blue/Middle/blue-middle-giant.png'
        BLUE_MIDDLE_SUPER = 'https://planet-story.s3.amazonaws.com/Stars/Blue/Middle/blue-middle-super.png'
        BLUE_OLD_DWARF = 'https://planet-story.s3.amazonaws.com/Stars/Blue/Old/blue-old-dwarf.png'
        BLUE_OLD_GIANT = 'https://planet-story.s3.amazonaws.com/Stars/Blue/Old/blue-old-giant.png'
        BLUE_OLD_SUPER = 'https://planet-story.s3.amazonaws.com/Stars/Blue/Old/blue-old-super.png'

        YELLOW_YOUNG_DWARF = 'https://planet-story.s3.amazonaws.com/Stars/Yellow/Young/yellow-young-dwarf.png'
        YELLOW_YOUNG_GIANT = 'https://planet-story.s3.amazonaws.com/Stars/Yellow/Young/yellow-young-giant.png'
        YELLOW_YOUNG_SUPER = 'https://planet-story.s3.amazonaws.com/Stars/Yellow/Young/yellow-young-super.png'
        YELLOW_MIDDLE_DWARF = 'https://planet-story.s3.amazonaws.com/Stars/Yellow/Middle/yellow-middle-dwarf.png'
        YELLOW_MIDDLE_GIANT = 'https://planet-story.s3.amazonaws.com/Stars/Yellow/Middle/yellow-middle-giant.png'
        YELLOW_MIDDLE_SUPER = 'https://planet-story.s3.amazonaws.com/Stars/Yellow/Middle/yellow-middle-super.png'
        YELLOW_OLD_DWARF = 'https://planet-story.s3.amazonaws.com/Stars/Yellow/Old/yellow-old-dwarf.png'
        YELLOW_OLD_GIANT = 'https://planet-story.s3.amazonaws.com/Stars/Yellow/Old/yellow-old-giant.png'
        YELLOW_OLD_SUPER = 'https://planet-story.s3.amazonaws.com/Stars/Yellow/Old/yellow-old-super.png'

        RED_MIDDLE_DWARF = 'https://planet-story.s3.amazonaws.com/Stars/Red/Middle/red-middle-dwarf.png'
        RED_MIDDLE_GIANT = 'https://planet-story.s3.amazonaws.com/Stars/Red/Middle/red-middle-giant.png'
        RED_MIDDLE_SUPER = 'https://planet-story.s3.amazonaws.com/Stars/Red/Middle/red-middle-super.png'
        RED_OLD_DWARF = 'https://planet-story.s3.amazonaws.com/Stars/Red/Old/red-old-dwarf.png'
        RED_OLD_GIANT = 'https://planet-story.s3.amazonaws.com/Stars/Red/Old/red-old-giant.png'
        RED_OLD_SUPER = 'https://planet-story.s3.amazonaws.com/Stars/Red/Old/red-old-super.png'
        RED_YOUNG_DWARF = 'https://planet-story.s3.amazonaws.com/Stars/Blue/Young/red-young-dwarf.png'
        RED_YOUNG_GIANT = 'https://planet-story.s3.amazonaws.com/Stars/Blue/Young/red-young-giant.png'
        RED_YOUNG_SUPER = 'https://planet-story.s3.amazonaws.com/Stars/Blue/Young/red-young-super.png'
