brightness = ["white", "red", "blue"]
StarSize = ["dwarf", "giant", "super"]
age = ["middleaged", "old", "young"]
distance = ["close", "midway", "far"]
atmosphere = ["hydrogen", "nitrogen", "oxygen"]
PlanetSize = ["large", "medium", "small"]
