Brightness = ["yellow", "red", "blue"]
StarSize = ["dwarf", "giant", "super"]
Age = ["middle-aged", "old", "young"]
Distance = ["near", "midway", "far"]
Atmosphere = ["hydrogen", "nitrogen", "oxygen"]
PlanetSize = ["large", "medium", "small"]
